#!/bin/bash
# Verification script for add-native-linux-support-with-wayland-primary-and--jx3xp10k
# Generated by relay-patch. Add patch-specific criteria below.
set -e

# Core: run the project's test suite
bun test

# Add patch-specific criteria here:
# Example:
# git diff --quiet upstream/main -- game.ts
# echo "" | bun run index.ts --some-flag | grep -q "expected output"
